apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: grafanas.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: Grafana
    listKind: GrafanaList
    plural: grafanas
    singular: grafana
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dashboard:
                  type: string
                datasources:
                  type: array
                  items:
                    type: string
                adminPassword:
                  type: string
                adminUser:
                  type: string
                plugins:
                  type: array
                  items:
                    type: string
