apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nodejsapphpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejsapp
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50   # Adjust as needed based on your application's CPU usage
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 70   # Adjust as needed based on your application's memory usage
